#!/bin/bash
module load openmpi-3.0.0
PREFIX=/mnt/home/jinyuyang/build
PROGLIST="papi-5.4.3 libunwind-1.3.1"

for prog in $PROGLIST
do
        export PATH=${PREFIX}/${prog}/bin64:${PREFIX}/${prog}/bin:$PATH
        export INCLUDE=${PREFIX}/${prog}/include64:${PREFIX}/${prog}/include:$INCLUDE
        export C_INCLUDE_PATH=${PREFIX}/${prog}/include64:${PREFIX}/${prog}/include:$C_INCLUDE_PATH
        export CPLUS_INCLUDE_PATH=${PREFIX}/${prog}/include64:${PREFIX}/${prog}/include:$CPLUS_INCLUDE_PATH
        export LIBRARY_PATH=${PREFIX}/${prog}/lib64:${PREFIX}/${prog}/lib:$LIBRARY_PATH
        export LD_LIBRARY_PATH=${PREFIX}/${prog}/lib64:${PREFIX}/${prog}/lib:$LD_LIBRARY_PATH:/usr/lib:/usr/lib64
done

export LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu/:$LD_LIBRARY_PATH
