#!/bin/bash
PREFIX=/mnt/home/jinyuyang/build
PROGLIST="papi-5.4.3 dyninst-10.1.0 libdwarf"

for prog in $PROGLIST
do
        export PATH=${PREFIX}/${prog}/bin64:${PREFIX}/${prog}/bin:$PATH
        export INCLUDE=${PREFIX}/${prog}/include64:${PREFIX}/${prog}/include:$INCLUDE
        export C_INCLUDE_PATH=${PREFIX}/${prog}/include64:${PREFIX}/${prog}/include:$C_INCLUDE_PATH
        export CPLUS_INCLUDE_PATH=${PREFIX}/${prog}/include64:${PREFIX}/${prog}/include:$CPLUS_INCLUDE_PATH
        export LIBRARY_PATH=${PREFIX}/${prog}/lib64:${PREFIX}/${prog}/lib:$LIBRARY_PATH
        export LD_LIBRARY_PATH=${PREFIX}/${prog}/lib64:${PREFIX}/${prog}/lib:$LD_LIBRARY_PATH:/usr/lib:/usr/lib64
done

export DYNINSTAPI_RT_LIB=/home/jinyuyang/workspace/build/dyninst-10.1.0/lib/libdyninstAPI_RT.so
export BAGUA_DIR=/home/jinyuyang/workspace/BaguaTool                                                                                                                                                                                      
export DYNINST_DIR=/mnt/home/jinyuyang/build/dyninst-10.1.0     
